package com.example.eventLog.enums;

public enum EventType {
    MESSAGE_SENT,
    MESSAGE_EDITED,
    MESSAGE_DELETED_FOR_ME,
    MESSAGE_DELETED_FOR_EVERYONE,
    CONVERSATION_CREATED,
    CONVERSATION_OPENED,
    CONVERSATION_CLOSED,
    PARTICIPANT_JOINED,
    PARTICIPANT_LEFT,
    CONVERSATION_ENDED,
    PARTICIPANT_RESTORED,
    LAST_CONVERSATION_REOPENED
}
