SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d9bt833bc2fs73b1d210-a.singapore-postgres.render.com:5432/vv_i7o4
SPRING_DATASOURCE_USERNAME: vv_user
SPRING_DATASOURCE_PASSWORD: 06Fl7DZF1Ax3wgeyj8AgtrEFLF8fNzdW

JWT_SECRET: dev-secret-32-characters-minimum-xx

REDIS_URL: redis://localhost:6379

app:
  security:
    public-urls:
      - /login
      - /register
      - /saveuser
      - /css/**
      - /js/**
      - /api/v1/auth/send-otp
      - /api/v1/auth/verify-otp
      - /api/v1/auth/refresh
      - /actuator/health
      - /ws/**
      - /favicon.ico
      - /api/v1/auth/me