SPRING_DATASOURCE_URL: jdbc:mysql://centerbeam.proxy.rlwy.net:49789/VV?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: jSgAkyEBehekDLdTZJYcStZmCsEvCmAZ

JWT_SECRET: dev-secret-32-characters-minimum-xx

REDIS_URL: redis://default:yfksvJXhrXZSEshNCTgVgGFtlAGgmhBC@tokaido.proxy.rlwy.net:51828

app:
  security:
    public-urls:
      - /login
      - /register
      - /saveuser
      - /css/**
      - /js/**
      - /api/v1/auth/send-otp
      - /api/v1/auth/verify-otp
      - /api/v1/auth/refresh
      - /actuator/health
      - /ws/**
      - /favicon.ico
      - /api/v1/auth/me